name: xc
favicon: null
layout_spectrum: 0.50626
typography_spectrum: 0.5805686034727842
title: XENNEN CONSULTING
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#000000'
    - '#151515'
    - '#231717'
    - '#240000'
  brandStrength: 0.9079116831999272
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.657585809705779
purpose: []
